[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
scroll = "https://sepolia-rpc.scroll.io/"
vanar = "https://rpc-vanguard.vanarchain.com"

[profile.scroll]
chain_id = 534351

[profile.vanar]
chain_id = 78600

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
